# Generated by Django 2.2.7 on 2019-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kxyzauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True, verbose_name='用户何时注册的时间'),
        ),
    ]
