# Generated by Django 2.2.7 on 2019-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kxyzauth', '0002_auto_20191120_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱,可以为空字符串'),
        ),
    ]
