"""
Django settings for kxyz project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm=$*)xe3d^j0m$@_@&0fou(%_shq5luct@(v+-=2kq@tr9vloa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.payinfo',
    'apps.course',
    'apps.kxyzauth',
    'apps.cms',
    'apps.news',
    'apps.ueditor',
    'rest_framework',
    'debug_toolbar'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kxyz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 模板文件(templates)的路径
        'DIRS': [os.path.join(BASE_DIR, 'front', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 配置模板的static标签
            'builtins': [
                'django.templatetags.static'
            ]
        },
    },
]

WSGI_APPLICATION = 'kxyz.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kxyz',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'kxyzauth.User'

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211'
    }
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# 配置好语言
LANGUAGE_CODE = 'zh-Hans'

# 配置时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# 静态文件路径配置
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front', 'dist')
]

MEDIA_URL = '/media/'
# media文件夹的路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 七牛配置
QINIU_ACCESS_KEY = ''
QINIU_SERCRET_KEY = ''
QINIU_BUCKET_NAME = ''
QINIU_DOMAIN = ''

# Ueditor文件上传到七牛云
UEDITOR_UPLOAD_TO_QINIU = True
UEDITOR_QINIU_ACCESS_KEY = QINIU_ACCESS_KEY
UEDITOR_QINIU_SECRET_KEY = QINIU_SERCRET_KEY
UEDITOR_QINIU_BUCKET_NAME = QINIU_BUCKET_NAME
UEDITOR_QINIU_DOMAIN = QINIU_DOMAIN

# Ueditor文件上传到本地服务器
UEDITOR_UPLOAD_TO_SERVER = True
UEDITOR_UPLOAD_PATH = MEDIA_ROOT
UEDITOR_CONFIG_PATH = os.path.join(BASE_DIR, 'front', 'dist', 'ueditor', 'config.json')

# 一页展示新闻的数量
ONE_PAGE_NEWS_COUNT = 1

# django-debug-toolbar的配置
INTERNAL_IPS = ['127.0.0.1']
DEBUG_TOOLBAR_PANELS = [
    # 代表使用的是那个django的版本
    'debug_toolbar.panels.versions.VersionsPanel',
    # 用来计时,判断加载当前页面总共花的时间
    'debug_toolbar.panels.timer.TimerPanel',
    # 读取django中的配置信息
    'debug_toolbar.panels.settings.SettingsPanel',
    # 此面板显示HTTP请求和响应标头，以及来自WSGI环境的值的选择
    'debug_toolbar.panels.headers.HeadersPanel',
    # GET / POST / cookie会话变量显示
    'debug_toolbar.panels.request.RequestPanel',
    # SQL查询包括执行时间和解释每个查询的链接
    'debug_toolbar.panels.sql.SQLPanel',
    # 使用静态文件及其位置(通过staticfiles查找器)
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    # 使用的模板和上下文，以及它们的模板路径
    'debug_toolbar.panels.templates.TemplatesPanel',
    # 缓存查询。与Django的站点缓存不兼容吗
    'debug_toolbar.panels.cache.CachePanel',
    # 信号列表，它们的目标和接收器
    'debug_toolbar.panels.signals.SignalsPanel',
    # 通过Python的内置日志模块进行日志输出
    'debug_toolbar.panels.logging.LoggingPanel',
    # 启用此面板时，调试工具栏将在重定向时显示中间页面,
    # 以便您可以在重定向之前查看任何调试信息。此页面将提供一个指向重定向目的地的链接，
    # 您可以在准备就绪时跟随该链接,默认情况下不活动，可以使用disable_panel配置选项激活它
    'debug_toolbar.panels.redirects.RedirectsPanel',
    # 视图函数的概要信息,默认情况下无作用,可以使用disable_panel配置选项激活它
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

DEBUG_TOOLBAR_CONFIG = {
    'JQUERY': ''
}

# 百度云配置
BAIDU_CLOUD_USER_ID = ''
BAIDU_CLOUD_USER_KEY = ''
